### ISSUE TITLE
Bug反馈: 帮人代收取的时候总是收取的目标的上一名，导致一直循环。

### ISSUE THREAD

**Issue by sundi117** [kwu130/Alipay#7]

**Comment by kwu130** [comment]
这个是由于手机分辨率不同导致的，你可以找到ant_forest.js文件中的473行，对应代码为：
`    //找到好友，进入好友森林
    if(click(epoint[0].x, epoint[0].y))
    {
        //确认进入了好友森林
`
把epoint[0].y改成epoint[0].y+20，即将点击点的纵坐标向下偏移一点就行了（20这个值可能需要自己确定一下）。

**Comment by kwu130** [comment]
> No description provided.
@sundi117 
这个是由于手机分辨率不同导致的，你可以找到ant_forest.js文件中的473行，对应代码为：
`    //找到好友，进入好友森林
    if(click(epoint[0].x, epoint[0].y))
    {
        //确认进入了好友森林
`
把epoint[0].y改成epoint[0].y+20，即将点击点的纵坐标向下偏移一点就行了（20这个值可能需要自己确定一下）。

**Comment by sundi117** [comment]
感谢！晚上我回家试一下。
